### ISSUE TITLE
Suggest using a different phrase for "Use cases" link.

### ISSUE THREAD

**Issue by follower** [effekseer/Website#6]
One change I didn't include in #5 was for the "Use cases" link:

https://github.com/effekseer/Website/blob/eadb3a1e87126456bc5d9a84e3b25b62db98737d/locales/en.yml#L6

I'm not sure about the best replacement term but, to me, at least, the term "Use case" means "here's a generic situation where you can use this tool", rather than "here are some specific games that have used this tool".

Possible alternative terms:

 * "Case Study" (not entirely accurate as a term)
 * "Used by"
 * "As seen in"
 * "Gallery"
 * ...

(I know there is a commonly used phrase but my mind is drawing a blank currently. :) )

As some of the examples include some big names and platforms, I think a more descriptive link would really help communicate that this is a production ready tool, already used in production.

**Comment by durswd** [comment]
Thank you. I changed it into Used by
