### ISSUE TITLE
HTTPSの強制によるセキュリティ強化

### ISSUE THREAD

**Issue by esperecyan** [effekseer/Website#7]
GitHub Pagesの設定で、Enforce HTTPSへチェックを入れれば改善できると思います。
https://docs.github.com/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

また、ページ間のリンクも http:// になっている部分があります。

**Comment by durswd** [comment]
修正しましたのでご確認お願いします

**Comment by esperecyan** [comment]
確認しました。ご対応有り難うございます。
